### ISSUE TITLE
Issue with latest followthemoney update

### ISSUE THREAD

**Issue by joyindaride** [pudo/opensanctions#126]
Hi there, thank you very much for all your hard work. I hope you don't mind me posting this here but I don't know where else to look.
I'm having problems since yesterday and I think they are related to the latest followthemoney ver (2.7.0). When I run Opensanctions I get the following Type error
```
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/bin/opensanctions", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opensanctions/opensanctions/cli.py", line 4, in <module>
    from opensanctions.core import Dataset, Context, Entity, setup
  File "/opensanctions/opensanctions/core/__init__.py", line 3, in <module>
    from opensanctions.core.dataset import Dataset
  File "/opensanctions/opensanctions/core/dataset.py", line 4, in <module>
    from followthemoney import model
  File "/opt/followthemoney/followthemoney/__init__.py", line 14, in <module>
    model = Model(model_path)
  File "/opt/followthemoney/followthemoney/model.py", line 33, in __init__
    self.properties = set[Property]()
```
If a rollback to FTM's previous ver (2.6.2), I got another error:
```
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/bin/opensanctions", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opensanctions/opensanctions/cli.py", line 4, in <module>
    from opensanctions.core import Dataset, Context, Entity, setup
  File "/opensanctions/opensanctions/core/__init__.py", line 3, in <module>
    from opensanctions.core.dataset import Dataset
  File "/opensanctions/opensanctions/core/dataset.py", line 8, in <module>
    from opensanctions.core.entity import Entity
  File "/opensanctions/opensanctions/core/entity.py", line 9, in <module>
    from opensanctions.helpers import type_lookup
  File "/opensanctions/opensanctions/helpers/__init__.py", line 4, in <module>
    from opensanctions.helpers.addresses import make_address, apply_address
  File "/opensanctions/opensanctions/helpers/addresses.py", line 2, in <module>
    from addressformatting import AddressFormatter
  File "/usr/local/lib/python3.8/dist-packages/addressformatting/__init__.py", line 1, in <module>
    from addressformatting.format import AddressFormatter
  File "/usr/local/lib/python3.8/dist-packages/addressformatting/format.py", line 4, in <module>
    from addressformatting.util import clean_address, first, render
  File "/usr/local/lib/python3.8/dist-packages/addressformatting/util.py", line 1, in <module>
    import pystache
  File "/usr/local/lib/python3.8/dist-packages/pystache/__init__.py", line 2, in <module>
    from init import *
ModuleNotFoundError: No module named 'init'

```
I don't know if I'm doing something wrong here... Thank you very much.

**Comment by pudo** [comment]
hey! welcome to the project :) With regards to the pystache error: that's new to me, too, let me look into it. 

with regards to the first issue: I think I made a release of ftm yesterday that only works on py 3.9. might need to go back and fix that, since 3.8 seems to be super widespread. is running 3.9 at all an option for you?

**Comment by pudo** [comment]
Hmm, can you tell me what your pystache version is? I have:

```bash
$ pip freeze | grep pystache
pystache==0.5.4
```

**Comment by joyindaride** [comment]
Hello! Thank you very much for the reply!
No problem with Python 3.9. I've now tried FTM 2.7 independently and it works perfect ;)

However I still get the same two errors with opensanctions even with 3.9. Regarding pystache, I have on my environment pystache==0.5.4 too, put in the opensanctions shell it's pystache==0.5.0

In fact, now that I look at the build, there are errors related to pystache:
```
Collecting pystache
  Downloading pystache-0.5.4.tar.gz (75 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehz4vmup/pystache_5170ace93be34f8bab206ed92220172a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehz4vmup/pystache_5170ace93be34f8bab206ed92220172a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mo17t9ai
         cwd: /tmp/pip-install-ehz4vmup/pystache_5170ace93be34f8bab206ed92220172a/
    Complete output (3 lines):
    pystache: using: version '58.0.4' of <module 'setuptools' from '/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py'>
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz#sha256=f7bbc265fb957b4d6c7c042b336563179444ab313fb93a719759111eabd3b85a (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pystache-0.5.3.tar.gz (74 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehz4vmup/pystache_5fd1a1aa8e4d4e228b4af2131dabce5f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehz4vmup/pystache_5fd1a1aa8e4d4e228b4af2131dabce5f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-al453i4p
         cwd: /tmp/pip-install-ehz4vmup/pystache_5fd1a1aa8e4d4e228b4af2131dabce5f/
    Complete output (3 lines):
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    pystache: using: version '58.0.4' of <module 'setuptools' from '/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py'>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/08/e6/c0345da4dbccdcd4d4054e77ba3b9064d05064564d4b9d5978d07b2aab7d/pystache-0.5.3.tar.gz#sha256=445c8663291abf11305693ecac7b9f3ff976555f5506ccc05a0353260a5a16dc (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pystache-0.5.2.tar.gz (61 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehz4vmup/pystache_fc1390628f4c4399bfa6f51e8b8c41e4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehz4vmup/pystache_fc1390628f4c4399bfa6f51e8b8c41e4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mkhd3yzm
         cwd: /tmp/pip-install-ehz4vmup/pystache_fc1390628f4c4399bfa6f51e8b8c41e4/
    Complete output (2 lines):
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/88/4c/3d35fc4b70e621b133c54ecd510e36d30b16e86f88d0b70b2a6c026988d4/pystache-0.5.2.tar.gz#sha256=d6fae441217c4912c6839e5309bb8b3db213dac15a01f3fc5b7063d7261a5f59 (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pystache-0.5.1.tar.gz (55 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehz4vmup/pystache_4d64499248fb42748a451b1d683e430c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehz4vmup/pystache_4d64499248fb42748a451b1d683e430c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1m6bcwtt
         cwd: /tmp/pip-install-ehz4vmup/pystache_4d64499248fb42748a451b1d683e430c/
    Complete output (2 lines):
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2c/f1/0622fa9984ee547bc26ab8de95962248f33203ce44478a6f72e65b8507a4/pystache-0.5.1.tar.gz#sha256=686dc38b97397c9bf04e4cf0f90e5a5ffc58fa85f60864f1b6d70d7786113a75 (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by pudo** [comment]
Ok so `pystache` is dead since 2014. Maybe I should move `addressformatting` to this: https://github.com/noahmorrison/chevron

**Comment by pudo** [comment]
Try `pip install -U addressformatting` :)

**Comment by pudo** [comment]
fwiw, followthemoney 2.7.1 should be running on python 3.8 again.

**Comment by joyindaride** [comment]
Works like a charm now <chef's kiss>. Latest FtM version, tested on Python 3.8 and 3.9. Thank you so much, keep up the great work!!!

**Comment by pudo** [comment]
Woo! Closing :)
