### ISSUE TITLE
RuntimeError: The dataset has no entry point!

### ISSUE THREAD

**Issue by SarunasCard** [pudo/opensanctions#78]
Hello,
few crawlers: `eu_cor_members`, `gb_coh_disqualified`, `interpol_yellow_notices` give error:
```
root@b07be929e868:/opt/followthemoney/docs# opensanctions crawl eu_cor_members
2021-03-10 06:07:28 [info     ] Begin crawl                    [eu_cor_members] 
2021-03-10 06:07:28 [error    ] Crawl failed                   [eu_cor_members]
Traceback (most recent call last):
  File "/opensanctions/opensanctions/core/context.py", line 69, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/core/dataset.py", line 59, in method
    raise RuntimeError("The dataset has no entry point!")
RuntimeError: The dataset has no entry point!
```
Should I add something like  `entry_point: opensanctions.crawlers.eu_cor_members` to each of the /metadata/*.yml if `entry_point` is missing?

**Comment by pudo** [comment]
Just pushed some refactor I had lying around, this might fix some fo them (`eu_cor_members` needs some more coding). 

btw this is undergoing a pretty major re-vamp, I wouldn't really expect it work all the time in the interim. Hoping to work full-time on it during the summer. Wanna help?
