### ISSUE TITLE
ModuleNotFoundError: No module named 'ftmstore.memorious'

### ISSUE THREAD

**Issue by SarunasCard** [pudo/opensanctions#79]
Hello,
running a crawler give error:
```
root@b07be929e868:/opt/followthemoney/docs# opensanctions crawl eu_cor_members
2021-03-10 06:20:21 [info     ] Begin crawl                    [eu_cor_members] 
2021-03-10 06:20:21 [error    ] Crawl failed                   [eu_cor_members] 
Traceback (most recent call last):
  File "/opensanctions/opensanctions/core/context.py", line 69, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/core/dataset.py", line 62, in method
    module = import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opensanctions/opensanctions/crawlers/eu_cor_members.py", line 2, in <module>
    from ftmstore.memorious import EntityEmitter
ModuleNotFoundError: No module named 'ftmstore.memorious'
```
The `pip freeze` output:
```
alephclient==2.2.2
Babel==2.9.0
banal==1.0.5
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
countrynames==1.7.1
cryptography==3.4.6
decorator==4.4.2
et-xmlfile==1.0.1
fingerprints==1.0.3
# Editable install with no version control (followthemoney==2.3.2)
-e /opt/followthemoney
# Editable install with no version control (followthemoney-enrich==2.3.2)
-e /opt/followthemoney/enrich
followthemoney-store==3.0.2
idna==2.10
isodate==0.6.0
jdcal==1.4.1
languagecodes==1.0.9
lxml==4.6.2
networkx==2.5
normality==2.1.3
openpyxl==3.0.6
# Editable install with no version control (opensanctions==3.0.0)
-e /opensanctions
pantomime==0.4.1
phonenumbers==8.12.18
psycopg2==2.8.4
psycopg2-binary==2.8.6
pycparser==2.20
pycrypto==2.6.1
PyICU==2.4.2
pyOpenSSL==20.0.1
pyparsing==2.4.7
python-Levenshtein==0.12.2
python-stdnum==1.16
pytz==2021.1
PyYAML==5.4.1
rdflib==5.0.0
redis==3.5.3
requests==2.25.1
requests-cache==0.5.2
requests-toolbelt==0.9.1
six==1.15.0
SQLAlchemy==1.3.23
stringcase==1.2.0
structlog==21.1.0
text-unidecode==1.3
urllib3==1.26.3
urlnormalizer==1.2.5
xlrd==2.0.1
```
Is it something wrong with the `followthemoney` versions?

**Comment by pudo** [comment]
In order to fix that scraper, it needs to be ported to the new framework. In this case that comes down to removing the `EntityEmitter` entirely and replacing it with `context.emit`.
